// Copyright 2023-2026 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.

/*********************************/
/* AUTOGENERATED. DO NOT MODIFY! */
/*********************************/

// Use src_rat_fir_gen.py script to regenerate this file
// python src_rat_fir_gen.py -gc True -nt 48

#ifndef _SRC_RAT_48T_DS_COEFS_H_
#define _SRC_RAT_48T_DS_COEFS_H_

#include <stdint.h>

#ifndef ALIGNMENT
#  ifdef __xcore__
#    define ALIGNMENT(N)  __attribute__((aligned (N)))
#  else
#    define ALIGNMENT(N)
#  endif
#endif

#define SRC_RAT_FIR_48T_DS_NUM_TAPS (48)
#define SRC_RAT_FIR_48T_DS_NUM_PHASES (2)
#define SRC_RAT_FIR_48T_DS_TAPS_PER_PHASE (24)

/** q30 coefficients to use for the 48 -> 32 kHz polyphase rational factor 48t downsampling */
extern const int32_t src_rat_fir_48t_ds_coefs[SRC_RAT_FIR_48T_DS_NUM_PHASES][SRC_RAT_FIR_48T_DS_TAPS_PER_PHASE];

#endif // _SRC_RAT_48T_DS_COEFS_H_
