// Copyright 2023-2026 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.

/*********************************/
/* AUTOGENERATED. DO NOT MODIFY! */
/*********************************/

// Use src_rat_fir_gen.py script to regenerate this file
// python src_rat_fir_gen.py -gc True -nt 48

#include "src_rat_fir_48t_ds_coefs.h"
#include <stdint.h>

/** q30 coefficients to use for the 48 -> 32 kHz polyphase rational factor 48t downsampling */
const int32_t ALIGNMENT(8) src_rat_fir_48t_ds_coefs[SRC_RAT_FIR_48T_DS_NUM_PHASES][SRC_RAT_FIR_48T_DS_TAPS_PER_PHASE] = {
    {
          -836279,     -1511853,      4633855,     -3331393,     -5205286,     14094115,
         -9447157,    -13998500,     38329634,    -27797034,    -47620793,    226309753,
        342129244,     66484670,    -71415051,     23608611,     15631718,    -23045498,
          8619065,      5719490,     -8365728,      2961045,      1793971,     -2267583,
    },
    {
         -2267583,      1793971,      2961045,     -8365728,      5719490,      8619065,
        -23045498,     15631718,     23608611,    -71415051,     66484670,    342129244,
        226309753,    -47620793,    -27797034,     38329634,    -13998500,     -9447157,
         14094115,     -5205286,     -3331393,      4633855,     -1511853,      -836279,
    },
};
