#!/usr/bin/env python
import xmostest, sys, subprocess

if __name__ == "__main__":
    if sys.platform.startswith("darwin"):
        p = subprocess.Popen("ulimit -n 1024", shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        for line in p.stdout.readlines():
            print line,
        retval = p.wait()
        #OSX has a very low limit on open files - 256. Each spawn of xsim consumes about 5 so to run the 144 tests in this repo, we need at least 720 spare
    xmostest.init()
    xmostest.register_group("lib_src", "asrc_test", "Test ASRC conversion across sample rates",
                        "This test iterates through all input and output sample rates using input 1KHz sine at 0db and 10/11KHz intermodulation tones. It checks the output against golden results generated by the original ASRC deliverable from Digimath.")
    xmostest.register_group("lib_src", "ssrc_test", "Test SSRC conversion across sample rates",
                        "This test iterates through all input and output sample rates using input 1KHz sine at 0db and 10/11KHz intermodulation tones. It checks the output against golden results generated by the original SSRC deliverable from Digimath.")
    xmostest.register_group("lib_src", "fixed_factor_of_3_tests", "Test fixed factor of 3 conversion functions.",
                            "These tests check the DS3 and OS3 functions.")

    xmostest.runtests()
    xmostest.finish()
