TARGET = XCORE-AI-EXPLORER
APP_NAME =
USED_MODULES = lib_src
XCC_FLAGS = -O2 -DASRC_N_CHANNELS=1 -report -fcmdline-buffer-bytes=1024
SOURCE_DIRS=dut/src

include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common

