def configure(conf):
    conf.load('xwaf.compiler_xcc')


def build(bld):
    bld.env.PROJECT_ROOT = '../../..'
    bld.env.XCC_FLAGS = ['-O2', '-g', '-report', '-fcmdline-buffer-bytes=512']
    bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'

    depends_on = ['lib_src']
    prog = bld.program(source='ssrc_test.xc', depends_on=depends_on)
